# Generated by Django 5.1.1 on 2024-09-05 10:46

import django.db.models.deletion
import django.utils.timezone
import setup.models
import setup.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=230, null=True, validators=[setup.validations.is_valid_string])),
                ('email', models.CharField(max_length=230, null=True, unique=True, validators=[setup.validations.is_valid_string])),
                ('password', models.CharField(max_length=230, null=True, validators=[setup.validations.is_valid_password])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=230, null=True, validators=[setup.validations.is_valid_password])),
                ('status', models.CharField(default='send', max_length=230, null=True, validators=[setup.validations.is_valid_password])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', setup.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('from_user', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='setup.user')),
                ('to_user', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to='setup.user')),
            ],
        ),
    ]
